TheGathering/TheGathering.Web/Models/Volunteer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TheGathering.Web.Models
{
    public class Volunteer
    {
        public int Id { get; set; }
        [Display(Name = "First Name")]
        public String FirstName { get; set; }
        [Display(Name = "Last Name")]
        public String LastName { get; set; }
        [Display(Name = "Date of Birth")]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime Birthday { get; set; }
        [Display(Name = "Email")]
        public String Email { get; set; }
        [Display(Name = "Phone Number")]
        public String PhoneNumber { get; set; }
        [Display(Name = "Interest in Leadership")]
        public Boolean InterestInLeadership { get; set; }
        [Display(Name = "Sign Up for Newsletter")]
        public Boolean SignUpForNewsLetter { get; set; }
        public List<VolunteerVolunteerEvent> VolunteerVolunteerEvents { get; set; }
        public string ApplicationUserId { get; set; }

        [Display(Name = "Account Active")]
        public bool IsAccountActive { get; set; }

        public Volunteer()
        {
            IsAccountActive = true;
        }
    }
}

TheGathering/TheGathering.Web/ViewModels/Volunteer/VolunteerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TheGathering.Web.Models;

namespace TheGathering.Web.ViewModels.VolunteerModels
{
    public class VolunteerViewModel
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime Birthday { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public bool InterestInLeadership { get; set; }
        public bool SignUpForNewsLetter { get; set; }
        public List<Models.VolunteerEvent> VolunteerEvents { get; set; }
        public string ApplicationUserId { get; set; }

        public VolunteerViewModel(Volunteer volunteer)
        {
            Id = volunteer.Id;
            FirstName = volunteer.FirstName;
            LastName = volunteer.LastName;
            Birthday = volunteer.Birthday;
            Email = volunteer.Email;
            PhoneNumber = volunteer.PhoneNumber;
            InterestInLeadership = volunteer.InterestInLeadership;
            SignUpForNewsLetter = volunteer.SignUpForNewsLetter;
            ApplicationUserId = volunteer.ApplicationUserId;
        }
    }
}

TheGathering/TheGathering.Web/ViewModels/VolunteerModels/SignUpEventViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TheGathering.Web.Models;

namespace TheGathering.Web.ViewModels.VolunteerModels
{
    public class SignUpEventViewModel
    {
        public Volunteer Volunteer { get; set; }
        public Models.VolunteerEvent VolunteerEvent { get; set; }
        public List<Volunteer> Volunteers { get; set; }
    }
}

TheGathering/TheGathering.Web/ViewModels/VolunteerModels/UserEventsListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TheGathering.Web.Models;
namespace TheGathering.Web.ViewModels.VolunteerModels
{
    public class UserEventsListViewModel
    {
        public List<Models.VolunteerEvent> VolunteerEvents { get; set; }
        public List<Models.VolunteerEvent> CancelledEvents { get; set; }
        public List<Models.VolunteerEvent> CurrentEvents { get; set; }
        public List<Models.VolunteerEvent> PastEvents { get; set; }
        public Volunteer Volunteer { get; set; }

    }
}

TheGathering/TheGathering.Web/Controllers/VolunteerEventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Data;
using TheGathering.Web.Models;
using TheGathering.Web.Services;
using TheGathering.Web.ViewModels.VolunteerModels;

namespace TheGathering.Web.Controllers
{
    public class VolunteerEventController : BaseController
    {
        private CalendarService service = new CalendarService();
        private MealSiteService mealSiteService = new MealSiteService();

        public const string INVALID_CALENDAR_DATES_ERROR = "The given Calendar dates are incorrect, make sure the start date is earlier than the end date.";

        private VolunteerService volunteerService = new VolunteerService();
        private VolunteerGroupService volunteerGroupService = new VolunteerGroupService();
        // GET: VolunteerEvent
        [Authorize(Roles = "volunteer,groupleader")]
        public ActionResult Index()
        {
            List<VolunteerEvent> events = service.GetAllEvents();

            return View(events);
        }
        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            VolunteerEventViewModel model = new VolunteerEventViewModel();
            model.DropDownItems = AllLocations();
            return View(model);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VolunteerEvent toBeDeleted = service.GetEventById((int)id);
            if (toBeDeleted == null)
            {
                return HttpNotFound();
            }

            toBeDeleted.MealSite = mealSiteService.GetMealSiteById(toBeDeleted.MealSite_Id);

            return View(toBeDeleted);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            VolunteerEvent toBeDeleted = service.GetEventById(id);
            service.DeleteEvent(toBeDeleted);
            //mealSiteService.DeleteVolunteerEvent(toBeDeleted.Id, toBeDeleted.MealSite.Id);
            return RedirectToAction("ManageEvents", "AdminPortal", null);
        }
        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(VolunteerEventViewModel viewModel)
        {
            viewModel.DropDownItems = AllLocations();
            if (viewModel.OpenSlots < 1)
            {
                ModelState.AddModelError("OpenSlots", "The number of open slots must be greater than 0");
            }
            if (ModelState.IsValid)
            {
                if (viewModel.StartingShiftTime.CompareTo(viewModel.EndingShiftTime) < 0)
                {
                    VolunteerEvent volunteerEvent = new VolunteerEvent(viewModel);
                    volunteerEvent.MealSite_Id = viewModel.MealSiteId;
                    service.AddEvent(volunteerEvent);

                    return RedirectToAction("ManageEvents", "AdminPortal", null);
                }

                viewModel.Error = INVALID_CALENDAR_DATES_ERROR;
                return View(viewModel);
            }

            return View(viewModel);
        }

        [Authorize(Roles = "groupleader")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VolunteerEvent volunteerEvent = service.GetEventById((int)id);

            if (volunteerEvent == null)
            {
                return HttpNotFound();
            }
            volunteerEvent.MealSite = mealSiteService.GetMealSiteById(volunteerEvent.MealSite_Id);
            SignUpEventViewModel signUpEventViewModel = new SignUpEventViewModel();
            Volunteer volunteer = GetCurrentVolunteer();

            List<int> IdList = volunteerEvent.VolunteerVolunteerEvents.Where(vve => !vve.IsItCanceled).Select(vve => vve.VolunteerId).ToList();
            signUpEventViewModel.Volunteer = volunteer;
            signUpEventViewModel.VolunteerEvent = volunteerEvent;
            signUpEventViewModel.Volunteers = volunteerService.GetVolunteersById(IdList);

            return View(signUpEventViewModel);
        }

        [Authorize(Roles = "volunteer")]
        public ActionResult VolunteerDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VolunteerEvent volunteerEvent = service.GetEventById((int)id);

            if (volunteerEvent == null)
            {
                return HttpNotFound();
            }
            volunteerEvent.MealSite = mealSiteService.GetMealSiteById(volunteerEvent.MealSite_Id);
            SignUpEventViewModel signUpEventViewModel = new SignUpEventViewModel();
            Volunteer volunteer = GetCurrentVolunteer();

            List<int> IdList = volunteerEvent.VolunteerVolunteerEvents.Where(vve => !vve.IsItCanceled).Select(vve => vve.VolunteerId).ToList();
            signUpEventViewModel.Volunteer = volunteer;
            signUpEventViewModel.VolunteerEvent = volunteerEvent;
            signUpEventViewModel.Volunteers = volunteerService.GetVolunteersById(IdList);

            return View(signUpEventViewModel);
        }

        [Authorize(Roles = "volunteer")]
        public ActionResult RemoveVolunteerFromEvent(int? eventID, int? volunteerID)
        {
            if (eventID == null || volunteerID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            volunteerService.RemoveVolunteerVolunteerEvent((int)volunteerID, (int)eventID);

            return RedirectToAction("EventUnregistered", "Volunteer", new { volunteerId = (int)volunteerID, eventId=(int)eventID});
        }

        [Authorize(Roles = "admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VolunteerEvent volunteerEvent = service.GetEventById((int)id);

            if (volunteerEvent == null)
            {
                return HttpNotFound();
            }

            VolunteerEventViewModel viewModel = new VolunteerEventViewModel(volunteerEvent)
            {
                DropDownItems = AllLocations(),
                MealSite = mealSiteService.GetMealSiteById(volunteerEvent.MealSite_Id),
                MealSiteId = volunteerEvent.MealSite_Id
            };

            return View(viewModel);
        }
        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MealSiteId, Id, StartingShiftTime, EndingShiftTime, OpenSlots, Location, Description")] VolunteerEventViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                if (viewModel.StartingShiftTime.CompareTo(viewModel.EndingShiftTime) < 0)
                {
                    VolunteerEvent volunteerEvent = new VolunteerEvent(viewModel);
                    volunteerEvent.MealSite_Id = viewModel.MealSiteId;
                    service.SaveEdits(volunteerEvent);

                    return RedirectToAction("ManageEvents", "AdminPortal", null);
                }

                viewModel.Error = INVALID_CALENDAR_DATES_ERROR;
                viewModel.DropDownItems = AllLocations();
                return View(viewModel);
            }
            return View(viewModel);
        }


        [Authorize(Roles ="volunteer")]
        public ActionResult VolunteerCalendar()
        {
            ViewModels.VolunteerCalendarViewModel viewModel = new ViewModels.VolunteerCalendarViewModel();
            viewModel.Volunteer = GetCurrentVolunteer();
            viewModel.VolunteerEvents = new List<VolunteerEvent>();

            foreach (VolunteerEvent volunteerEvent in service.GetAllEvents())
            {
                VolunteerEvent ve = volunteerEvent;
                ve.VolunteerVolunteerEvents = new List<VolunteerVolunteerEvent>();
                var events = volunteerService.GetVolunteerVolunteerEvents(GetCurrentVolunteer().Id);
                if (events != null)
                {
                    ve.VolunteerVolunteerEvents = events;
                }
                viewModel.VolunteerEvents.Add(ve);
            } 
            return View(viewModel);
        }
        [Authorize(Roles = "groupleader")]
        public ActionResult Calendar()
        {
            ViewModels.VolunteerGroupCalendarViewModel viewModel = new ViewModels.VolunteerGroupCalendarViewModel();
            viewModel.VolunteerGroupLeader = GetCurrentVolunteerGroupLeader();
            viewModel.VolunteerEvents = new List<VolunteerEvent>();

            foreach (VolunteerEvent volunteerEvent in service.GetAllEvents())
            {
                VolunteerEvent ve = volunteerEvent;
                ve.VolunteerGroupVolunteerEvents = new List<VolunteerGroupVolunteerEvent>();
                var events = volunteerGroupService.GetVolunteerGroupVolunteerEvents(GetCurrentVolunteerGroupLeader().Id);
                if (events != null)
                {
                    ve.VolunteerGroupVolunteerEvents = events;
                }
                viewModel.VolunteerEvents.Add(ve);
            }
            return View(viewModel);
        }

        public JsonResult GetEvents()
        {
            var events = service.GetAllEvents();

            foreach (var item in events)
            {
                item.MealSite.VolunteerEvents = null;
            }

            return new JsonResult { Data = events, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }


        public List<SelectListItem> AllLocations()
        {

TheGathering/TheGathering.Web/Views/Volunteer/CancelSignUpEvent.cshtml
@model TheGathering.Web.ViewModels.VolunteerModels.SignUpEventViewModel
@{
    ViewBag.Title = "SignUpEvent";
}

<h2>Cancel this Event</h2>

<div>
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.VolunteerEvent.StartingShiftTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VolunteerEvent.StartingShiftTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VolunteerEvent.EndingShiftTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VolunteerEvent.EndingShiftTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VolunteerEvent.MealSite.AddressLine1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VolunteerEvent.MealSite.AddressLine1)
        </dd>
    </dl>
    <p>
        Are you sure you would like to cancel this volunteer event?
    </p>
	<p>
		@Html.ActionLink("Yes", "EventUnregistered", new { volunteerId = Model.Volunteer.Id, eventId = Model.VolunteerEvent.Id }, new { @class = "btn btn-large btn-danger" })
		@Html.ActionLink("No", "Details", "Volunteer", new { id = Model.Volunteer.Id }, new { @class = "btn btn-large btn-primary" })
	</p>
</div>

TheGathering/TheGathering.Web/Views/Volunteer/Deactivate.cshtml
@model TheGathering.Web.Models.Volunteer

@{
    ViewBag.Title = "Delete";
}
<div class="col-sm-8">
    <h1>Delete</h1>

    <h3>Are you sure you want to deactivate this account?</h3>
    <hr />
    <h3>First Name</h3>
    <p>
        @Html.DisplayFor(model => model.FirstName)
    </p>

    <h3>Last Name</h3>
    <p>
        @Html.DisplayFor(model => model.LastName)
    </p>

    <h3>Birthday</h3>
    <p>
        @Html.DisplayFor(model => model.Birthday)
    </p>

    <h3>Email</h3>
    <p>
        @Html.DisplayFor(model => model.Email)
    </p>

    <h3>Phone Number</h3>
    <p>
        @Html.DisplayFor(model => model.PhoneNumber)
    </p>

    <h3>Interest in Leadership</h3>
    <p>
        @Html.DisplayFor(model => model.InterestInLeadership)
    </p>

    <h3>Sign up for Newsletter</h3>
    <p>
        @Html.DisplayFor(model => model.SignUpForNewsLetter)
    </p>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.Id)
        <div class="form-actions no-color">
            <input type="submit" value="Deactivate" class="btn btn-primary" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TheGathering/TheGathering.Web/Views/Volunteer/Edit.cshtml
@model TheGathering.Web.Models.Volunteer

@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <h1>My Profile</h1>

        <hr />

        <div class="row">
            <div class="form-group">
                <label class="col-sm-1 h2font">Name</label>
            </div>
        </div>

        <div class="row">
            <div class="form-group">
                <div class="col-sm-6">
                    @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control", placeholder = "First Name" } })
                    @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                </div>
                <div class="col-sm-6">
                    @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control", placeholder = "Last Name" } })
                    @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <br />

        <div class="row">
            <div class="form-group">
                <label class="col-sm-6 @*control-label*@, h2font">Phone Number</label>
                <label class="col-sm-5 @*control-label*@, h2font">Birthday</label>
            </div>
        </div>

        <div class="row">
            <div class="form-group">
                <div class="col-sm-6">
                    @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control", placeholder = "###-###-####" } })
                    @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                </div>
                <div class="col-sm-6">
                    @Html.EditorFor(model => model.Birthday, new { htmlAttributes = new { @class = "form-control", placeholder = "mm / dd / yyyy" } })
                    @Html.ValidationMessageFor(model => model.Birthday, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <br />

        <div class="row">
            <div class="form-group form-check" style="padding-left:15px">
                @Html.EditorFor(model => model.SignUpForNewsLetter)
                @Html.ValidationMessageFor(model => model.SignUpForNewsLetter, "", new { @class = "text-danger" })
                <label class="form-check-label pfont">I Would Like To Recieve The Gathering Newsletter</label>
            </div>
        </div>
        @Html.HiddenFor(model => model.Email)
        @Html.HiddenFor(model => model.InterestInLeadership)
        @Html.HiddenFor(model => model.VolunteerVolunteerEvents)
        @Html.HiddenFor(model => model.ApplicationUserId)

        <p>
            @Html.ActionLink("Change your password?", "ForgotPassword", "Account")
        </p>

        <div class="row">
            <div class="col-sm-1">
                <div class="form-group">
                    <input type="submit" class="btn btn-primary" value="Save" />
                </div>
            </div>
            <div class="col-sm-1">
                @Html.ActionLink("Back to Calendar", "VolunteerCalendar", "VolunteerEvent", null, new { @class = "btn btn-primary" })
            </div>
        </div>
        
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TheGathering/TheGathering.Web/Views/Volunteer/EventAlreadyRegistered.cshtml
@model TheGathering.Web.Models.Volunteer
@{
	ViewBag.Title = "EventRegistered";
}

<h2>Event Already Registered</h2>

<div>
	<p>
		You have already registered for this event!
	</p>
	<p>
		@Html.ActionLink("Back to Event List", "Index", "VolunteerEvent", null, new { @class = "btn btn-primary" })
		@Html.ActionLink("To Calendar", "VolunteerCalendar", "VolunteerEvent", null, new { @class = "btn btn-primary" })
		@Html.ActionLink("See Your Events", "UserEventsList", null, new { @class = "btn btn-info" })
</div>

TheGathering/TheGathering.Web/Views/Volunteer/EventNotRegistered.cshtml
@{
    ViewBag.Title = "Event Not Registered";
}

<h2>EventAlreadyRegistered</h2>

<div>
    You've Haven't Registered for this Event!
    <p>
        @Html.ActionLink("Back to Event List", "Index", "VolunteerEvent", null, null)
    </p>
    <p>
        @Html.ActionLink("To Calendar", "VolunteerCalendar", "VolunteerEvent", null, null)
    </p>
    <p>
        @Html.ActionLink("See Your Events", "UserEventsList", null, null)
    </p>
</div>

TheGathering/TheGathering.Web/Views/Volunteer/EventRegistered.cshtml
@model TheGathering.Web.Models.Volunteer
@{
    ViewBag.Title = "EventRegistered";
}

<h2>Event Registered</h2>

<div>
    <p>
        Thank you for registering for this event!
    </p>
   
    <p>
        @Html.ActionLink("Back To Calendar", "VolunteerCalendar", "VolunteerEvent", null, new { @class = "btn btn-primary" })

        @Html.ActionLink("See Your Events", "UserEventsList", null, new { @class = "btn btn-primary" }) 
    </p>
   

</div>

TheGathering/TheGathering.Web/Views/Volunteer/LeadershipEmailConfirm.cshtml
@{
    ViewBag.Title = "Email Sent";
}

    <div class="row">
        <h1>Thank you for your interest!</h1>
        <p>One of our team members will send you an email about your interest in leadership as soon as possible.</p>
        @if (User.IsInRole("volunteer"))
        {
            @Html.ActionLink("Back to calendar", "VolunteerCalendar", "VolunteerEvent", null, new { @class = "btn btn-primary" })
        }
        @if (User.IsInRole("groupleader"))
        {
            @Html.ActionLink("Back to calendar", "Calendar", "VolunteerGroup", null, new { @class = "btn btn-primary" })

        }
    </div>

TheGathering/TheGathering.Web/Views/Volunteer/SignUpEvent.cshtml
@model TheGathering.Web.ViewModels.VolunteerModels.SignUpEventViewModel
@{
    ViewBag.Title = "SignUpEvent";
}

<h2>Sign Up for Event</h2>

<div>
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.VolunteerEvent.StartingShiftTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VolunteerEvent.StartingShiftTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VolunteerEvent.EndingShiftTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VolunteerEvent.EndingShiftTime)
        </dd>

        <dt>
            Meal Site
        </dt>
        <dd>
            @Html.DisplayFor(model => model.VolunteerEvent.MealSite.Name)
        </dd>
        <dd>
            @Html.DisplayFor(model => model.VolunteerEvent.MealSite.AddressLine1)
        </dd>
        <dd>
            @Html.DisplayFor(model => model.VolunteerEvent.MealSite.City), @Html.DisplayFor(model => model.VolunteerEvent.MealSite.State) @Html.DisplayFor(model => model.VolunteerEvent.MealSite.Zipcode)
        </dd>
    </dl>
    <p>
        Are you sure you would like to sign up for this volunteer event?
    </p>

        @Html.ActionLink("Yes", "EventRegistered", new { volunteerId = Model.Volunteer.Id, eventId = Model.VolunteerEvent.Id }, new { @class = "btn btn-primary" })

        @Html.ActionLink("No", "Details", "VolunteerEvent", new { id = Model.VolunteerEvent.Id }, new { @class = "btn btn-primary" })

</div>

TheGathering/TheGathering.Web/Views/Volunteer/UserEventsList.cshtml
@model TheGathering.Web.ViewModels.VolunteerModels.UserEventsListViewModel

@{
    ViewBag.Title = "UserEventsList";
}
<script>
    $(document).ready(function () {
        $('[data-toggle="tooltip"]').tooltip();
    });
</script>
<h2>Your Report</h2>

<div class="row">
    <div class="col-sm-6">
        <h5font>
            Monthly Frequency: @ViewBag.monthlyFrequency events
        </h5font>
        <a class="no-print" href="#" data-toggle="tooltip" title="Monthly Frequency of a volunteer shows the amount of times they volunteer per month. In order for the number to be greater than 0, they must have been with The Gathering for at least a month.">
            <img height="16" src="~/Content/question-mark-icon-24x24.png" />
        </a>
        <h5>
            Time with The Gathering: @ViewBag.timeWithGathering days
        </h5>
        <a></a>
        <h5>
            Total Volunteer Hours: @ViewBag.totalHours hours and @ViewBag.totalMinutes minutes
        </h5>
    </div>

    <div class="col-sm-6">
        @Html.ActionLink("Go to Calendar", "VolunteerCalendar", "VolunteerEvent", null, new { @class = "btn btn-primary" })
    </div>
</div>

@if (Model.CurrentEvents.Count > 0)
{
    <div class="row">
        <div class="col-sm-6">
            <h2>Current Events</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.VolunteerEvents[0].StartingShiftTime)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.VolunteerEvents[0].EndingShiftTime)
                    </th>

                    <th>
                        Meal Site
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.VolunteerEvents[0].Description)
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model.CurrentEvents)
                {
                    <tr>
                        <td>
                            @item.StartingShiftTime.ToString("g")
                        </td>
                        <td>
                            @item.EndingShiftTime.ToString("g")
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.MealSite.Name)<br />
                            @Html.DisplayFor(modelItem => item.MealSite.AddressLine1)<br />
                            @Html.DisplayFor(modelItem => item.MealSite.City), @Html.DisplayFor(modelItem => item.MealSite.State) @Html.DisplayFor(modelItem => item.MealSite.Zipcode)

                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td>
                            @Html.ActionLink("Cancel Signup", "RemoveVolunteerFromEvent", "VolunteerEvent", new { eventId = item.Id, volunteerId = Model.Volunteer.Id }, new { @class = "btn btn-primary" })
                        </td>
                    </tr>
                }

            </table>
        </div>
    </div>
}

else
{
    <h3>You are not currently signed up for any events</h3>
}

@if (Model.PastEvents.Count > 0)
{
    <div class="row">
        <div class="col-sm-12">
            <h2>Past Events</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.VolunteerEvents[0].StartingShiftTime)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.VolunteerEvents[0].EndingShiftTime)
                    </th>

                    <th>
                        Meal Site
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.VolunteerEvents[0].Description)
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model.PastEvents)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.StartingShiftTime)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.EndingShiftTime)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.MealSite.Name)<br />
                            @Html.DisplayFor(modelItem => item.MealSite.AddressLine1)<br />
                            @Html.DisplayFor(modelItem => item.MealSite.City), @Html.DisplayFor(modelItem => item.MealSite.State) @Html.DisplayFor(modelItem => item.MealSite.Zipcode)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td>
                            @Html.ActionLink("Details", "VolunteerDetails", "VolunteerEvent", new { id = item.Id }, new { @class = "btn btn-primary" })
                        </td>
                    </tr>
                }

            </table>
        </div>
    </div>
}