TheGathering/TheGathering.Web/ViewModels/VolunteerGroup/GroupEventsListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TheGathering.Web.Models;

namespace TheGathering.Web.ViewModels.VolunteerGroup
{
    public class GroupEventsListViewModel
    {
        public List<VolunteerGroupVolunteerEvent> VolunteerGroupEvents { get; set; }

        public List<Models.VolunteerEvent> VolunteerEvents { get; set; }


    }
}

TheGathering/TheGathering.Web/ViewModels/VolunteerGroup/GroupNumberEventsListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TheGathering.Web.Models;

namespace TheGathering.Web.ViewModels.VolunteerGroup
{
    public class GroupNumberEventsListViewModel
    {
        public List<VolunteerGroupVolunteerEvent> VolunteerGroupEvents { get; set; }
        public List<Models.VolunteerEvent> VolunteerEvents { get; set; }
        //public List<Models.VolunteerEvent> CancelledEvents { get; set; }
        public List<Models.VolunteerGroupVolunteerEvent> CurrentEvents { get; set; }
        public List<Models.VolunteerGroupVolunteerEvent> PastEvents { get; set; }
        public VolunteerGroupLeader volunteerGroupLeader { get; set; }
    }
}

TheGathering/TheGathering.Web/ViewModels/VolunteerGroup/SignUpGroupViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TheGathering.Web.Models;

namespace TheGathering.Web.ViewModels.VolunteerGroup
{
    public class SignUpGroupViewModel
    {
        public int VolunteerGroupLeaderID { get; set; }
        public int VolunteerEventID { get; set; }
        public VolunteerGroupLeader VolunteerGroupLeader { get; set; }
        public Models.VolunteerEvent VolunteerEvent { get; set; }
        public int VolunteerSlots { get; set; }
    }
}

TheGathering/TheGathering.Web/Controllers/VolunteerGroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TheGathering.Web.Models;
using TheGathering.Web.Services;
using TheGathering.Web.ViewModels.VolunteerGroup;

namespace TheGathering.Web.Controllers
{
    
    public class VolunteerGroupController : BaseController
    {
        // GET: VolunteerGroup
        
        VolunteerGroupService _service = new VolunteerGroupService();
        CalendarService _eventService = new CalendarService();
        MealSiteService _mealSiteService = new MealSiteService();

        [Authorize(Roles = "admin")]
        public ActionResult Index()
        {
            var model = _service.GetAllVolunteerGroups();

            if (model == null)
            {
                model = new List<VolunteerGroupLeader>();
            }

            return View(model);
        }
        [Authorize(Roles = "groupleader")]
        public ActionResult SignUpGroupEvent(int eventId)
        {
            SignUpGroupViewModel model = new SignUpGroupViewModel();
            var VolunteerGroupLeader = GetCurrentVolunteerGroupLeader();
            int volunteerId = VolunteerGroupLeader.Id;
            var volunteerEventIds = _service.GetVolunteerGroupEvents(volunteerId);
            bool alreadyRegistered = volunteerEventIds.Any(id => id == eventId);
            if (alreadyRegistered)
            {
                return RedirectToAction("EventAlreadyRegistered");
            }
            model.VolunteerGroupLeader = _service.GetLeaderById(volunteerId);
            model.VolunteerEvent = _eventService.GetEventById((int)eventId);
            model.VolunteerGroupLeaderID = model.VolunteerGroupLeader.Id;
            model.VolunteerEventID = model.VolunteerEvent.Id;
            //TO DO: Change Hardcoding (model.VolunteerGroupLeader.Id)
            var events = _eventService.GetEventsByIds(volunteerEventIds);
            return View(model);
        }
        [HttpPost]
        [Authorize(Roles = "groupleader")]
        public ActionResult SignUpGroupEvent(SignUpGroupViewModel signUpGroupViewModel)
        {
            int numVolunteers = signUpGroupViewModel.VolunteerSlots;
            int eventId = signUpGroupViewModel.VolunteerEventID;
            signUpGroupViewModel.VolunteerEvent = _eventService.GetEventById(eventId);
            signUpGroupViewModel.VolunteerGroupLeader = GetCurrentVolunteerGroupLeader();
            int volunteerId = signUpGroupViewModel.VolunteerGroupLeader.Id;
            var origOpenSlots = _eventService.GetEventById(eventId).OpenSlots;
            var volunteerEvent = _eventService.GetEventById(eventId);
            if (signUpGroupViewModel.VolunteerSlots<1)
            {
                ModelState.AddModelError("VolunteerSlots", "The number of volunteers cannot be less than 1.");
            }
            if (origOpenSlots < numVolunteers)
            {
                ModelState.AddModelError("VolunteerSlots", "There are only "+origOpenSlots+" volunteer slots available.");
            }

            if (ModelState.IsValid)
            {
                _service.ReduceOpenSlots(volunteerEvent, origOpenSlots, numVolunteers);
                _service.AddVolunteerGroupVolunteerEvent(volunteerId, eventId, numVolunteers);
                return RedirectToAction("GroupEventsList");
            }
            GetCurrentVolunteerGroupLeader().TotalGroupMembers = numVolunteers;
            return View(signUpGroupViewModel);
        }
        public ActionResult EventAlreadyRegistered()
        {
            return View();
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]

        public ActionResult Create(VolunteerGroupLeader volunteergroupleader)
        {
            if (ModelState.IsValid)
            {
                _service.CreateLeader(volunteergroupleader);
                return RedirectToAction("Index");
            }
            return View();

        }

        [Authorize(Roles = "groupleader")]
        public ActionResult Edit(int? id)
        {
            VolunteerGroupLeader vgl ;
            if (id != null && User.IsInRole("admin"))
            {
                vgl = _service.GetLeaderById((int)id);
            }
            else
            {
                vgl = GetCurrentVolunteerGroupLeader();
            }
            if (vgl == null)
            {
                return HttpNotFound();
            }

            return View(vgl);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "groupleader")]
        public ActionResult Edit(VolunteerGroupLeader volunteergroupleader)
        {
            if (volunteergroupleader.LeaderEmail.Contains('.') == false)
            {
                ModelState.AddModelError("Email", "Email must contain a period");
            }
            if (volunteergroupleader.LeaderEmail.Contains('@') == false)
            {
                ModelState.AddModelError("Email", "Email must contain an @");
            }
            if (volunteergroupleader.TotalGroupMembers<0)
            {
                ModelState.AddModelError("TotalGroupMembers", "Total Group Members must be greater than 0");
            }
            /***
            if (volunteergroupleader.LeaderPhoneNumber.Length > 11)
            {
                ModelState.AddModelError("LeaderPhoneNumber", "Phone number must be shorter than 11 numbers");
            }
            if (volunteergroupleader.LeaderPhoneNumber.Any(char.IsDigit) == false)
            {
                ModelState.AddModelError("LeaderPhoneNumber", "Phone number must not have non-numeric characters in it.");
            }***/
            if (ModelState.IsValid)
            {
                _service.EditLeader(volunteergroupleader);
                return RedirectToAction("Index");
            }
            return View(volunteergroupleader);
        }
        [Authorize(Roles = "groupleader")]
        public ActionResult Details(int id)
        {
            return View(_service.GetLeaderById(id));
        }
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VolunteerGroupLeader volunteergroupleader = _service.GetLeaderById((int)id);
            if (volunteergroupleader == null)
            {
                return HttpNotFound();
            }
            return View(volunteergroupleader);
        }
        [HttpPost]
        public ActionResult Delete(int id)
        {
            VolunteerGroupLeader volunteergroupleader = _service.GetLeaderById(id);
            _service.DeleteLeader(volunteergroupleader);
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "groupleader")]
        public ActionResult GetEventsByIds(List<int> eventId)
        {
            List<VolunteerEvent> volunteerEvents = _eventService.GetEventsByIds(eventId);
            return View(volunteerEvents);
        }
        [Authorize(Roles = "groupleader")]
        public ActionResult GroupEventsList()
        {
            //var volunteergroup = GetCurrentVolunteerGroupLeader();

            //GroupNumberEventsListViewModel viewModel = new GroupNumberEventsListViewModel();
            //viewModel.VolunteerGroupEvents = volunteergroup.VolunteerGroupVolunteerEvents;

            
            //return View(viewModel);

            var volunteerGroupLeader = GetCurrentVolunteerGroupLeader();
            var events = volunteerGroupLeader.VolunteerGroupVolunteerEvents.Select(vgve => vgve.VolunteerEvent).ToList();
           
            //var cancelledEventIds = _service.GetCancelledVolunteerEventIdsByVolunteerId(volunteer.Id);
            //var cancelledEvents = _eventService.GetEventsByIds(cancelledEventIds);

            events.Sort(new SortByDate());
            //cancelledEvents.Sort(new SortByDate());
            List<VolunteerGroupVolunteerEvent> CurrentEvents = new List<VolunteerGroupVolunteerEvent>();
            List<VolunteerGroupVolunteerEvent> PastEvents = new List<VolunteerGroupVolunteerEvent>();
            foreach (VolunteerGroupVolunteerEvent item in volunteerGroupLeader.VolunteerGroupVolunteerEvents)
            {
                if (!item.IsItCanceled)
                {
                    var mealsite = _mealSiteService.GetMealSiteById(item.VolunteerEvent.MealSite_Id);
                    item.VolunteerEvent.MealSite = mealsite;
                    if (item.VolunteerEvent.StartingShiftTime > DateTime.Now)
                        CurrentEvents.Add(item);
                    else
                        PastEvents.Add(item);
                }
            }
            CurrentEvents.Sort(new SortByDateForVolunteerGroup());
            PastEvents.Sort(new SortByDateForVolunteerGroup());
            GroupNumberEventsListViewModel viewModel = new GroupNumberEventsListViewModel();
            viewModel.VolunteerEvents = events;
            //viewModel.CancelledEvents = cancelledEvents;
            viewModel.CurrentEvents = CurrentEvents;
            viewModel.PastEvents = PastEvents;
            viewModel.volunteerGroupLeader = volunteerGroupLeader;

            return View(viewModel);

        }
    }
    public class SortByDateForVolunteerGroup : IComparer<VolunteerGroupVolunteerEvent>
    {
        public int Compare(VolunteerGroupVolunteerEvent x, VolunteerGroupVolunteerEvent y)
        {
            return y.VolunteerEvent.StartingShiftTime.CompareTo(x.VolunteerEvent.StartingShiftTime);
        }
    }
}

TheGathering/TheGathering.Web/Views/VolunteerGroup/Delete.cshtml
@model TheGathering.Web.Models.VolunteerGroupLeader

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Volunteer Group Leader</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LeaderFirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LeaderFirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LeaderLastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LeaderLastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LeaderBirthday)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LeaderBirthday)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LeaderEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LeaderEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LeaderPhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LeaderPhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GroupName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GroupName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SignUpForNewsLetter)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SignUpForNewsLetter)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalGroupMembers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalGroupMembers)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TheGathering/TheGathering.Web/Views/VolunteerGroup/Details.cshtml
@model TheGathering.Web.Models.VolunteerGroupLeader

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Volunteer Group Leader</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LeaderFirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LeaderFirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LeaderLastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LeaderLastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LeaderBirthday)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LeaderBirthday)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LeaderEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LeaderEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LeaderPhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LeaderPhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GroupName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GroupName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SignUpForNewsLetter)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SignUpForNewsLetter)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalGroupMembers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalGroupMembers)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

TheGathering/TheGathering.Web/Views/VolunteerGroup/Edit.cshtml
@model TheGathering.Web.Models.VolunteerGroupLeader

@{
    ViewBag.Title = "Edit";
}



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="container">



        <div class="form-horizontal">
            <div class="row">
                <h1>My Profile</h1>
                <hr />
            </div>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)


            <div class="row">
                <div class="form-group">
                    <label class="col-sm-4 h2font">Leader Name</label>
                </div>
            </div>

            <div class="row">
                <div class="form-group">
                    <div class="col-sm-6">
                        @Html.EditorFor(model => model.LeaderFirstName, new { htmlAttributes = new { @class = "form-control", placeholder = "First Name" } })
                        @Html.ValidationMessageFor(model => model.LeaderFirstName, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-sm-6">
                        @Html.EditorFor(model => model.LeaderLastName, new { htmlAttributes = new { @class = "form-control", placeholder = "Last Name" } })
                        @Html.ValidationMessageFor(model => model.LeaderLastName, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="form-group">
                    <label class="col-sm-6 @*control-label*@, h2font">Phone Number</label>
                    <label class="col-sm-5 @*control-label*@, h2font">Birthday</label>
                </div>
            </div>

            <div class="row">
                <div class="form-group">
                    <div class="col-sm-6">
                        @Html.EditorFor(model => model.LeaderPhoneNumber, new { htmlAttributes = new { @class = "form-control", placeholder = "###-###-####" } })
                        @Html.ValidationMessageFor(model => model.LeaderPhoneNumber, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-sm-6">
                        @Html.EditorFor(model => model.LeaderBirthday, new { htmlAttributes = new { @class = "form-control", placeholder = "mm / dd / yyyy" } })
                        @Html.ValidationMessageFor(model => model.LeaderBirthday, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="form-group">
                    <label class="col-sm-6 @*control-label*@, h2font">Group Name</label>
                    <label class="col-sm-5 @*control-label*@, h2font">Total Group Members</label>
                </div>
            </div>

            <div class="row">
                <div class="form-group">
                    <div class="col-sm-6">
                        @Html.EditorFor(model => model.GroupName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.GroupName, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-sm-6">
                        @Html.EditorFor(model => model.TotalGroupMembers, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TotalGroupMembers, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="form-group">
                    <label class="col-sm-4 h2font">Leader Email</label>
                </div>
            </div>

            <div class="row">
                <div class="form-group">
                    <div class="col-sm-6">
                        @Html.EditorFor(model => model.LeaderEmail, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.LeaderEmail, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <br />

            <div class="row">
                <div class="form-group form-check" style="padding-left:15px">
                    @Html.EditorFor(model => model.SignUpForNewsLetter)
                    @Html.ValidationMessageFor(model => model.SignUpForNewsLetter, "", new { @class = "text-danger" })
                    <label class="form-check-label pfont">I Would Like To Receive The Gathering Newsletter</label>
                </div>
            </div>
            <div class="row">
                @Html.ActionLink("Change your password?", "ForgotPassword", "Account")
            </div>
            <div class="row">
                <div class="form-group">
                    <div>
                        <input type="submit" value="Save" class="btn btn-primary" />
                        @Html.ActionLink("Back to Calendar", "Calendar", "VolunteerEvent", null, new { @class = "btn btn-primary" })
                    </div>
                </div>
            </div>
        </div>
    </div>
}

TheGathering/TheGathering.Web/Views/VolunteerGroup/EventAlreadyRegistered.cshtml
@{
    ViewBag.Title = "EventAlreadyRegistered";
}

<h2>Event Already Registered</h2>
<p>You have already registered for this event.</p>
<br />

<p>
    @Html.ActionLink("Back To Calendar", "Calendar", "VolunteerEvent", null, null)
</p>
<p>
    @Html.ActionLink("See Your Events", "GroupEventsList", null, null)
</p>

TheGathering/TheGathering.Web/Views/VolunteerGroup/GroupEventsList.cshtml
@model TheGathering.Web.ViewModels.VolunteerGroup.GroupNumberEventsListViewModel
@{
    ViewBag.Title = "GroupEventsList";
}

<script>
    $(document).ready(function () {
        $('[data-toggle="tooltip"]').tooltip();
    });
</script>

@if (Model.CurrentEvents.Count > 0)
{
    <div class="row">
        <div class="col-sm-6">
            <h2>Current Events</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.VolunteerEvents[0].StartingShiftTime)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.VolunteerEvents[0].EndingShiftTime)
                    </th>

                    <th>
                        Meal Site
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.VolunteerEvents[0].Description)
                    </th>
                    <th>
                        Registered Slots
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model.CurrentEvents)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.VolunteerEvent.StartingShiftTime)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.VolunteerEvent.EndingShiftTime)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.VolunteerEvent.MealSite.Name)<br />
                            @Html.DisplayFor(modelItem => item.VolunteerEvent.MealSite.AddressLine1)<br />
                            @Html.DisplayFor(modelItem => item.VolunteerEvent.MealSite.City), @Html.DisplayFor(modelItem => item.VolunteerEvent.MealSite.State) @Html.DisplayFor(modelItem => item.VolunteerEvent.MealSite.Zipcode)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.VolunteerEvent.Description)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NumberOfGroupMembersSignedUp)
                        </td>
                        @*<td>
                                @Html.ActionLink("Cancel Signup", "RemoveVolunteerFromEvent", "VolunteerEvent", new { eventId = item.Id, volunteerId = Model.Volunteer.Id }, new { @class = "btn btn-primary" })
                            </td>*@
                    </tr>
                }

            </table>
        </div>
    </div>
}

else
{
    <h3>You are not currently signed up for any events</h3>
}

@if (Model.PastEvents.Count > 0)
{
    <div class="row">
        <div class="col-sm-12">
            <h2>Past Events</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.VolunteerEvents[0].StartingShiftTime)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.VolunteerEvents[0].EndingShiftTime)
                    </th>

                    <th>
                        Meal Site
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.VolunteerEvents[0].Description)
                    </th>
                    <th>
                        Registered Slots
                    </th>
                </tr>

                @foreach (var item in Model.PastEvents)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.VolunteerEvent.StartingShiftTime)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.VolunteerEvent.EndingShiftTime)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.VolunteerEvent.MealSite.Name)<br />
                            @Html.DisplayFor(modelItem => item.VolunteerEvent.MealSite.AddressLine1)<br />
                            @Html.DisplayFor(modelItem => item.VolunteerEvent.MealSite.City), @Html.DisplayFor(modelItem => item.VolunteerEvent.MealSite.State) @Html.DisplayFor(modelItem => item.VolunteerEvent.MealSite.Zipcode)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.VolunteerEvent.Description)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NumberOfGroupMembersSignedUp)
                        </td>
                        <td>
                            @Html.ActionLink("Details", "Details", "VolunteerEvent", new { id = item.Id }, new { @class = "btn btn-primary" })
                        </td>
                    </tr>
                }

            </table>
        </div>
    </div>
}
<p>
    @Html.ActionLink("Back to Calendar", "Calendar", "VolunteerEvent", null, new { @class = "btn btn-primary" })
</p>

TheGathering/TheGathering.Web/Views/VolunteerGroup/Index.cshtml
@model IEnumerable<TheGathering.Web.Models.VolunteerGroupLeader>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.GroupName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LeaderFirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LeaderLastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LeaderEmail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LeaderPhoneNumber)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.TotalGroupMembers)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.GroupName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.LeaderFirstName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.LeaderLastName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.LeaderEmail)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.LeaderPhoneNumber)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.TotalGroupMembers)
    </td>
    <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
    </td>
</tr>
}

</table>

TheGathering/TheGathering.Web/Views/VolunteerGroup/SignUpGroupEvent.cshtml
@model TheGathering.Web.ViewModels.VolunteerGroup.SignUpGroupViewModel

@{
    ViewBag.Title = "SignUpGroupEvent";
}

<h2>Sign-Up Group Event</h2>
@using (Html.BeginForm("SignUpGroupEvent", "VolunteerGroup", FormMethod.Post))
{

    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.VolunteerEvent.StartingShiftTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VolunteerEvent.StartingShiftTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VolunteerEvent.EndingShiftTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VolunteerEvent.EndingShiftTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VolunteerEvent.MealSite.AddressLine1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VolunteerEvent.MealSite.AddressLine1)
        </dd>
    </dl>
    @Html.HiddenFor(model => model.VolunteerGroupLeaderID)
    @Html.HiddenFor(model => model.VolunteerEventID)
    
    <p>
        Your Group:
        @Html.DisplayFor(model => model.VolunteerGroupLeader.GroupName)
    </p>
    <p>
        How many people would you like to sign up for this volunteer event?
    </p>
    <div class="form-group">
        <div class="col-md-10">
            @Html.EditorFor(model => model.VolunteerSlots, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.VolunteerSlots, "", new { @class = "text-danger" })
        </div>
    </div>
    
    <div class="form-group">
        <div class="col-md-offset-0 col-md-12">
            <br />
            <input type="submit" class="btn btn-primary" value="Sign Up" id="submit" />

            <!-- volunteerId = Model.VolunteerGroupLeader.Id, eventId = Model.VolunteerEvent.Id -->
            @Html.ActionLink("Back to Calendar", "Calendar", "VolunteerEvent", null, new { @class = "btn btn-primary" })
        </div>
    </div>
}
<br />