TheGathering/TheGathering.Web/Models/VolunteerEvent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web.Mvc;

namespace TheGathering.Web.Models
{
    public class VolunteerEvent
    {
        public int Id { get; set; }
        [Display(Name = "Shift Start Time")]
        public DateTime StartingShiftTime { get; set; }

        [Display(Name = "Shift End Time")]
        public DateTime EndingShiftTime { get; set; }
        [Display(Name = "Open Slots")]
        public int OpenSlots { get; set; }
        [Display(Name = "Meal Site")]
        public MealSite MealSite { get; set; }

        [ForeignKey("MealSite")]
        public int MealSite_Id { get; set; }
        
        public string Description { get; set; }
        public List<VolunteerVolunteerEvent> VolunteerVolunteerEvents { get; set; }
        public List<VolunteerGroupVolunteerEvent> VolunteerGroupVolunteerEvents { get; set; }
        public VolunteerEvent() { }

        public VolunteerEvent(VolunteerEventViewModel volunteerEvent)
        {
            Id = volunteerEvent.Id;
            StartingShiftTime = volunteerEvent.StartingShiftTime;
            EndingShiftTime = volunteerEvent.EndingShiftTime;
            OpenSlots = volunteerEvent.OpenSlots;
            Description = volunteerEvent.Description;
            VolunteerVolunteerEvents = volunteerEvent.VolunteerVolunteerEvents;
            MealSite_Id = volunteerEvent.MealSiteId;
        }
    }
}

TheGathering/TheGathering.Web/ViewModels/VolunteerEvent/AddVolunteerGroupViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TheGathering.Web.Models;

namespace TheGathering.Web.ViewModels
{
    public class AddVolunteerGroupViewModel
    {
        public Models.VolunteerEvent Event { get; set; }

        public List<VolunteerGroupLeader> AvailableVolunteerGroups { get; set; }

        public List<VolunteerGroupLeader> VolunteerGroupsToAdd { get; set; }
    }
}

TheGathering/TheGathering.Web/ViewModels/VolunteerEvent/AddVolunteerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TheGathering.Web.Models;

namespace TheGathering.Web.ViewModels
{
    public class AddVolunteerViewModel
    {
        public Models.VolunteerEvent Event { get; set; }

        public List<Volunteer> AvailableVolunteers { get; set; }

        public List<Volunteer> VolunteersToAdd { get; set; }
    }
}

TheGathering/TheGathering.Web/ViewModels/VolunteerEvent/SortedEventsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TheGathering.Web.Models;

namespace TheGathering.Web.ViewModels
{
    public class SortedEventsViewModel
    {
        public List<VolunteerEvent> Events { get; set; }
        public List<SelectListItem> SortItems { get; set; }
    }
}

TheGathering/TheGathering.Web/ViewModels/VolunteerEvent/VolunteerCalendarViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TheGathering.Web.Models;

namespace TheGathering.Web.ViewModels
{
    public class VolunteerCalendarViewModel
    {
        public List<Models.VolunteerEvent> VolunteerEvents { get; set; }
        public Volunteer Volunteer { get; set; }
    }
}

TheGathering/TheGathering.Web/ViewModels/VolunteerEvent/VolunteerEmailViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using TheGathering.Web.Models;

namespace TheGathering.Web.ViewModels
{
    public class VolunteerEmailViewModel
    {
        public int EventId { get; set; }

        public Models.VolunteerEvent VolunteerEvent { get; set; }

        public string Subject { get; set; }

        [DataType(DataType.MultilineText)]
        public string Message { get; set; }
    }
}

TheGathering/TheGathering.Web/ViewModels/VolunteerEvent/VolunteerEventViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheGathering.Web.Models
{
    public class VolunteerEventViewModel
    {
        public int Id { get; set; }
        [Display(Name = "Shift Start Time")]
        public DateTime StartingShiftTime { get; set; }

        [Display(Name = "Shift End Time")]
        public DateTime EndingShiftTime { get; set; }
        [Display(Name = "Open Slots")]
        public int OpenSlots { get; set; }

        public List<SelectListItem> DropDownItems { get; set; }
        public int MealSiteId { get; set; }
        [Display(Name = "Meal Site")]
        public MealSite MealSite { get; set; }

        public string Description { get; set; }

        public List<VolunteerGroupVolunteerEvent> VolunteerGroupVolunteerEvents { get; set; }

        public List<VolunteerVolunteerEvent> VolunteerVolunteerEvents { get; set; } = new List<VolunteerVolunteerEvent>();

        public List<Volunteer> SignedUpVolunteers { get; set; } = new List<Volunteer>();
        public List<VolunteerGroupLeader> SignedUpVolunteerGroups { get; set; } = new List<VolunteerGroupLeader>();

        /// <summary>
        /// This will be empty if there is no error, allows us to create an error for validating input information
        /// </summary>
        public string Error { get; set; }

        public VolunteerEventViewModel() { }

        public Volunteer volunteer { get; set; }

        public VolunteerEventViewModel(VolunteerEvent volunteerEvent)
        {
            Id = volunteerEvent.Id;
            StartingShiftTime = volunteerEvent.StartingShiftTime;
            EndingShiftTime = volunteerEvent.EndingShiftTime;
            OpenSlots = volunteerEvent.OpenSlots;
            MealSite = volunteerEvent.MealSite;
            MealSiteId = volunteerEvent.MealSite_Id;
            Description = volunteerEvent.Description;
            VolunteerVolunteerEvents = volunteerEvent.VolunteerVolunteerEvents;
        }
    }
}

TheGathering/TheGathering.Web/ViewModels/VolunteerEvent/VolunteerGroupCalendarViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TheGathering.Web.Models;

namespace TheGathering.Web.ViewModels
{
    public class VolunteerGroupCalendarViewModel
    {
        public List<Models.VolunteerEvent> VolunteerEvents { get; set; }
        public VolunteerGroupLeader VolunteerGroupLeader { get; set; }
    }
}

TheGathering/TheGathering.Web/Controllers/AdminPortalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using TheGathering.Web.Models;
using TheGathering.Web.Services;
using TheGathering.Web.ViewModels;
using TheGathering.Web.ViewModels.MealSite;
using TheGathering.Web.ViewModels.VolunteerModels;
using TheGathering.Web.ViewModels.VolunteerGroup;
using TheGathering.Web.ViewModels.Account;
using Microsoft.AspNet.Identity;
using System.Globalization;
using System.Text;
using TheGathering.Web.Sorting.VolunteerEventSorts;

namespace TheGathering.Web.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminPortalController : BaseController
    {

        // Services

        private VolunteerService volunteerService = new VolunteerService();
        private MealSiteService mealService = new MealSiteService();
        private CalendarService calendarService = new CalendarService();
        private VolunteerGroupService volunteerGroupService = new VolunteerGroupService();

        private Random rnd = new Random();

        // Basic pages


        // GET: AdminPortal
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Users()
        {
            var volunteers = volunteerService.GetAllActiveAndInactiveVolunteers();

            if (volunteers == null)
            {
                volunteers = new List<Volunteer>();
            }

            return View(volunteers);
        }

        public ActionResult ManageGroupLeaders()
        {
            return View(volunteerGroupService.GetAllVolunteerGroups());
        }

    public ActionResult MealSites()
        {

            return View(mealService.GetAllActiveAndInActiveMealSites());
        }

        public ActionResult ChangeMealSiteActivationConfirmation(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            MealSite meal = mealService.GetMealSiteById((int)id);

            if (meal == null)
            {
                return HttpNotFound();
            }
            MealSiteViewModel site = new MealSiteViewModel(meal);
            return View(site);
        }

        public ActionResult MealSiteActivationChange(int? id, bool? active)
        {
            if (active == null || id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            MealSite meal = mealService.GetMealSiteById((int)id);

            if (meal == null)
            {
                return HttpNotFound();
            }

            mealService.ChangeMealSiteActivation(meal, (bool)active);

            return RedirectToAction("MealSiteDetails", new { id = (int)id });
        }

        // Volunteer



        public Volunteer GetVolunteerById(int id)
        {
            return volunteerService.GetById(id);
        }

        public ActionResult ViewVolunteers(int eventID)
        {
            var evt = calendarService.GetEventById(eventID);
            var volunteerEventViewModel = new VolunteerEventViewModel(evt);
            List<int> IdList = evt.VolunteerVolunteerEvents.Where(vve => !vve.IsItCanceled).Select(vve => vve.VolunteerId).ToList();
            volunteerEventViewModel.SignedUpVolunteers = volunteerService.GetVolunteersById(IdList);
            List<int> groupList = evt.VolunteerGroupVolunteerEvents.ToList().Where(vgve => !vgve.IsItCanceled).Select(vgve => vgve.VolunteerGroupId).ToList();
            volunteerEventViewModel.SignedUpVolunteerGroups = volunteerGroupService.GetAllVolunteerGroups().Where(vg => groupList.Contains(vg.Id)).ToList();
            return View(volunteerEventViewModel);
        }

        public ActionResult ChangeAccountActivationConfirmation(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Volunteer vol = volunteerService.GetById((int)id);

            if (vol == null)
            {
                return HttpNotFound();
            }

            return View(vol);
        }
        public ActionResult ChangeLeaderActivationConfirmation(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            VolunteerGroupLeader lead = volunteerGroupService.GetLeaderById((int)id);

            if (lead == null)
            {
                return HttpNotFound();
            }

            return View(lead);
        }

        public ActionResult AccountActivationChange(int? id, bool? active)
        {
            if (active == null || id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Volunteer vol = volunteerService.GetById((int)id);

            if (vol == null)
            {
                return HttpNotFound();
            }

            volunteerService.ChangeVolunteerActivation(vol, (bool)active);

            return RedirectToAction("VolunteerDetails", new { id = (int)id });
        }
        public ActionResult LeaderActivationChange(int? id, bool? active)
        {
            if (active == null || id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            VolunteerGroupLeader lead = volunteerGroupService.GetLeaderById((int)id);

            if (lead == null)
            {
                return HttpNotFound();
            }

            volunteerGroupService.ChangeGroupLeaderActivation(lead, (bool)active);

            return RedirectToAction("GroupLeaderDetails", new { id = (int)id });
        }


        public ActionResult AddVolunteers(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            VolunteerEvent volunteerEvent = calendarService.GetEventById((int)id);

            if (volunteerEvent == null)
            {
                return HttpNotFound();
            }

            List<int> idList = volunteerEvent.VolunteerVolunteerEvents.Select(vve => vve.VolunteerId).ToList();
            List<Volunteer> signedUpVolunteers = volunteerService.GetVolunteersById(idList);
            List<Volunteer> addableVolunteers = volunteerService.GetAllVolunteers();

            foreach (Volunteer v in signedUpVolunteers)
            {
                var volVolEvent = volunteerEvent.VolunteerVolunteerEvents.Where(ctx => ctx.VolunteerId == v.Id).ToList();

                //If there's more than one item then they're most likely duplicates, there should only be one in this list
                if (volVolEvent.Count > 0 && volVolEvent[0].IsItCanceled) { continue; }

                addableVolunteers.Remove(v);
            }

            volunteerEvent.MealSite = mealService.GetMealSiteById(volunteerEvent.MealSite_Id);
            AddVolunteerViewModel viewModel = new AddVolunteerViewModel
            {
                Event = volunteerEvent,
                AvailableVolunteers = addableVolunteers
            };

            return View(viewModel);
        }

        public ActionResult AddVolunteerGroups(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            VolunteerEvent volunteerEvent = calendarService.GetEventById((int)id);

            if (volunteerEvent == null)
            {
                return HttpNotFound();
            }

            List<int> idList = volunteerEvent.VolunteerGroupVolunteerEvents.Select(vve => vve.VolunteerGroupId).ToList();
            List<VolunteerGroupLeader> signedUpVolunteerGroups = volunteerGroupService.GetAllVolunteerGroups().Where(vg => idList.Contains(vg.Id)).ToList();
            List<VolunteerGroupLeader> addableVolunteerGroups = volunteerGroupService.GetAllVolunteerGroups();

            foreach (VolunteerGroupLeader v in signedUpVolunteerGroups)
            {
                var vgve = volunteerGroupService.GetAllVolunteerGroupVolunteerEvents().Where(ctx => ctx.VolunteerGroupId == v.Id).ToList();

                //If there's more than one item then they're most likely duplicates, there should only be one in this list
                if (vgve.Count > 0 && vgve[0].IsItCanceled) { continue; }

                addableVolunteerGroups.Remove(v);
            }

            volunteerEvent.MealSite = mealService.GetMealSiteById(volunteerEvent.MealSite_Id);
            AddVolunteerGroupViewModel viewModel = new AddVolunteerGroupViewModel
            {
                Event = volunteerEvent,
                AvailableVolunteerGroups = addableVolunteerGroups
            };

            return View(viewModel);
        }

        public async Task<ActionResult> ResetUserPass(int? volunteerID)
        {
            if (volunteerID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Volunteer volunteer = volunteerService.GetById((int)volunteerID);

            ApplicationUser user = await UserManager.FindByNameAsync(volunteer.Email);

            // Secret Sauce ;D
            string userCode = await UserManager.GeneratePasswordResetTokenAsync(user.Id);
            string callbackUrl = Url.Action("ResetPassword", "Account", new { userId = user.Id, code = userCode }, protocol: Request.Url.Scheme);

            //await UserManager.SendEmailAsync(user.Id, "Reset Password", "Please reset your password by clicking <a href=\"" + callbackUrl + "\">here</a>");

TheGathering/TheGathering.Web/Views/VolunteerEvent/Create.cshtml
@model TheGathering.Web.Models.VolunteerEventViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@if (Model != null && !string.IsNullOrEmpty(Model.Error))
{
    <div class="alert alert-danger" role="alert">
        Error: @(Model.Error)
    </div>
}

@using (Html.BeginForm())
{
@Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Volunteer Event</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.StartingShiftTime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.StartingShiftTime, new { htmlAttributes = new { @class = "form-control", @type = "datetime-local" } })
            @Html.ValidationMessageFor(model => model.StartingShiftTime, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EndingShiftTime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EndingShiftTime, new { htmlAttributes = new { @class = "form-control", @type = "datetime-local" } })
            @Html.ValidationMessageFor(model => model.EndingShiftTime, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.OpenSlots, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.OpenSlots, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.OpenSlots, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MealSite, htmlAttributes: new { @class = "control-label col-md-2" })

        <div class="col-md-10">
            @Html.DropDownListFor(model => model.MealSiteId, Model.DropDownItems, new { @class = "form-control" } )
            @Html.ValidationMessageFor(model => model.MealSiteId, "", new { @class = "text-danger" })
        </div>
    </div>
    

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
		<div class="col-md-offset-2 col-md-10">
			<input type="submit" value="Create" class="btn btn-primary" />
			@Html.ActionLink("Back to List", "ManageEvents", "AdminPortal", null, new { @class = "btn btn-primary" })
		</div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
}

TheGathering/TheGathering.Web/Views/VolunteerEvent/Delete.cshtml
@model TheGathering.Web.Models.VolunteerEvent

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>VolunteerEvent</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StartingShiftTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartingShiftTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndingShiftTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndingShiftTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OpenSlots)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OpenSlots)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MealSite.AddressLine1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MealSite.AddressLine1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-primary" />
            @Html.ActionLink("Back to List", "ManageEvents", "AdminPortal", null, new { @class = "btn btn-primary" })
        </div>
    }
</div>

TheGathering/TheGathering.Web/Views/VolunteerEvent/Details.cshtml
@model TheGathering.Web.ViewModels.VolunteerModels.SignUpEventViewModel


@{
    ViewBag.Title = "Details";
}
<script type="text/javascript" src="~/Scripts/Bing Maps/BMaps2.js"></script>
<h1>Details</h1>

<div>
    <!--

    Displays the Id of event
    <h4 class="minorHeading"> ID = (at symbol)Html.DisplayFor(model => model.VolunteerEvent.Id)</h4>
    -->
    <hr />
    <div class="row">
        <div class="col-sm-6">
            <dl class="dl-horizontal">
                <dt>
                    Location
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.VolunteerEvent.MealSite.Name)<br />
                    @Html.DisplayFor(model => model.VolunteerEvent.MealSite.AddressLine1)<br />
                    @Html.DisplayFor(model => model.VolunteerEvent.MealSite.City), @Html.DisplayFor(model => model.VolunteerEvent.MealSite.State) @Html.DisplayFor(model => model.VolunteerEvent.MealSite.Zipcode)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.VolunteerEvent.StartingShiftTime)
                </dt>

                <dd>
                    @Model.VolunteerEvent.StartingShiftTime.ToString("g")
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.VolunteerEvent.EndingShiftTime)
                </dt>

                <dd>
                    @Model.VolunteerEvent.EndingShiftTime.ToString("g")
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.VolunteerEvent.OpenSlots)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.VolunteerEvent.OpenSlots)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.VolunteerEvent.Description)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.VolunteerEvent.Description)
                </dd>
            </dl>
            @if (Model.Volunteer != null && Model.VolunteerEvent.StartingShiftTime > DateTime.Now)
            {
                bool signedUp = false;
                foreach (var item in Model.Volunteers)
                {
                    if (item.Id.Equals(Model.Volunteer.Id))
                    {
                        signedUp = true;
                    }
                }
                if (signedUp)
                {
                    @Html.ActionLink("Cancel Signup", "RemoveVolunteerFromEvent", new { eventId = Model.VolunteerEvent.Id, volunteerId = Model.Volunteer.Id }, new { @class = "btn btn-primary" })
                }
                else
                {
                    @Html.ActionLink("Sign Up", "SignUpEvent", "Volunteer", new { eventId = Model.VolunteerEvent.Id, userId = Model.Volunteer.ApplicationUserId }, new { @class = "btn btn-primary" })
                }
            }
            else if (Model.VolunteerEvent.StartingShiftTime > DateTime.Now)
            {
                if (!User.IsInRole("groupleader"))
                {
                    @Html.ActionLink("Login to sign up", "Login", "Account", null, new { @class = "btn btn-primary" })
                }
            }
            else
            {
                <h3>This event has already passed</h3>
            }
            @Html.ActionLink("Back to Calendar", "Calendar", null, new { @class = "btn btn-primary" })
        </div>
        <div class="col-sm-6">
            <div id="myMap"></div>
        </div>
    </div>
</div>
@*Commented out because there were two signup buttons, this could have possible happened because of a merge conflict. *@
@*@Html.ActionLink("Sign Up", "SignUpEvent", "Volunteer", new { volunteerId = Model.Volunteer, eventId = Model.VolunteerEvent.Id }, new { @class = "btn btn-primary" })*@

<script>
    @Html.Raw("locations.push(new Location('" + Model.VolunteerEvent.MealSite.AddressLine1 + ", " + Model.VolunteerEvent.MealSite.City + "', "+ Model.VolunteerEvent.MealSite.Id +"," + Model.VolunteerEvent.MealSite.Latitude + "," + Model.VolunteerEvent.MealSite.Longitude + ",'" + Model.VolunteerEvent.MealSite.Name + "'," + Model.VolunteerEvent.MealSite.IsTheGatheringSite.ToString().ToLower() + "));")
</script>
<script type='text/javascript' src='https://www.bing.com/api/maps/mapcontrol?callback=init&key=Au02QBwR7dBBUZiE9NK_er_E7iVbAFbx9EsiHxA3xLOTK6ry7J-Okb9DqZEW98qb' async defer></script>

TheGathering/TheGathering.Web/Views/VolunteerEvent/Edit.cshtml
@model TheGathering.Web.Models.VolunteerEventViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@if (Model != null && !string.IsNullOrEmpty(Model.Error))
{
    <div class="alert alert-danger" role="alert">
        Error: @(Model.Error)
    </div>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>VolunteerEvent</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.StartingShiftTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartingShiftTime, new { htmlAttributes = new { @class = "form-control", @type = "datetime-local", @Value = Request.Browser.Browser=="Chrome" ? Model.StartingShiftTime.ToString("yyyy-MM-ddTHH:mm:ss") : Model.StartingShiftTime.ToString() } })
                @Html.ValidationMessageFor(model => model.StartingShiftTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndingShiftTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndingShiftTime, new { htmlAttributes = new { @class = "form-control", @type = "datetime-local", @Value = Request.Browser.Browser == "Chrome" ? Model.EndingShiftTime.ToString("yyyy-MM-ddTHH:mm:ss") : Model.EndingShiftTime.ToString() } })
                @Html.ValidationMessageFor(model => model.EndingShiftTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OpenSlots, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OpenSlots, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OpenSlots, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MealSite, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.MealSiteId, Model.DropDownItems, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MealSiteId, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="Save" class="btn btn-success" />
				@Html.ActionLink("Back to List", "ManageEvents", "AdminPortal", null, new { @class = "btn btn-primary" })
			</div>
        </div>
    </div>
}

TheGathering/TheGathering.Web/Views/VolunteerEvent/PrintView.cshtml
@{
    Layout = "~/Views/VolunteerEvent/_PrintLayout.cshtml";
    ViewBag.Title = "PrintView";
}

<h2>PrintView</h2>